<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefineConstants>HAZEL_BAG</DefineConstants>
        <RootNamespace>Next.Hazel</RootNamespace>
        <AssemblyName>Next.Hazel</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>NextFast.Hazel</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>Hazel.UnitTests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' != 'net6.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.3" />
        <PackageReference Include="Serilog" Version="4.2.1-dev-02352" />
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.3" />
        <PackageReference Include="Serilog" Version="4.2.1-dev-02352" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Next.Hazel.Abstractions\Next.Hazel.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Hazel.nuspec" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.0-beta.114" />
    </ItemGroup>

</Project>

