<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <RootNamespace>Next.Hazel.Abstractions</RootNamespace>
        <AssemblyName>Next.Hazel.Abstractions</AssemblyName>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

</Project>
